cmake_minimum_required(VERSION 3.16)
project(brain_raster LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(brain_raster main.cpp bytecode.cpp)
target_compile_options(brain_raster PRIVATE -O3 -Wall -Wextra -Wpedantic)
find_package(ZLIB REQUIRED)
target_link_libraries(brain_raster PRIVATE ZLIB::ZLIB)

add_executable(bfml_compiler ../film_machine/bfml_compiler.cpp bytecode.cpp)
target_compile_options(bfml_compiler PRIVATE -O3 -Wall -Wextra -Wpedantic)

add_executable(brain_brc_render bytecode_renderer.cpp bytecode.cpp)
target_compile_options(brain_brc_render PRIVATE -O3 -Wall -Wextra -Wpedantic)
target_link_libraries(brain_brc_render PRIVATE ZLIB::ZLIB)
